### ISSUE TITLE
[PE-D] Documentation bug: photo not rendering in the User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W12-4/tp#171]
Platform: Google Chrome

Result photo not loading in the user guide section 4.2
![bug 8.JPG](https://raw.githubusercontent.com/Agentum07/ped/main/files/44a50f23-86eb-4499-ad37-2ac09da4cde3.JPG)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Agentum07/ped#9

**Comment by ngjiayuan** [comment]
not a replicable problem
